URL_SERVICE = "https://cnt-1254abc5-092c-4ac5-a2eb-649e85979f58.containerhub.tripleten-services.com"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
FAKR_URL = "FAKE_TO_USE_IN_GIT_COMMAND"
